// <auto-generated />
namespace CalendarApp.DbModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class eventfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201711121217060_event-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
